/*
 * File: main.cpp
 * ----------------
 * This file is automatically generated.
 */

#include "mainwindow.h"
#include "difficulty.h"
#include <QApplication>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    w.show();
    return a.exec();
}
