/*
 * File: quit.h
 * --------------
 * This file is automatically generated for the quit dialog.
 */

#ifndef QUIT_H
#define QUIT_H

#include <QDialog>

namespace Ui {
class Quit;
}

class Quit : public QDialog
{
    Q_OBJECT

public:
    explicit Quit(QWidget *parent = 0);
    ~Quit();

private:
    Ui::Quit *ui;
};

#endif // QUIT_H
